{% set name = "orbax-checkpoint" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orbax_checkpoint-{{ version }}.tar.gz
  sha256: 16eac956ab827fefda47a31a66f76be305ab4eeb1fbe6672b844a85c2457333d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - flit-core >=3.5,<4
    - pip
  run:
    - simplejson >=3.16.0
    - python >=3.10
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jax >=0.4.34
    - numpy
    - pyyaml
    - tensorstore >=0.1.68
    - nest-asyncio
    - protobuf
    - humanize
    - importlib_resources

test:
  imports:
    - orbax.checkpoint
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Orbax Checkpoint
  home: https://github.com/google/orbax
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - bwohlberg
