{% set name = "orbax-checkpoint" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orbax_checkpoint-{{ version }}.tar.gz
  sha256: dd8a71712f9cc9f283d798c301f8cfe8d8515cf75473c88e048f498d97649ddc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.5,<4
    - pip
  run:
    - python >=3.9
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jax >=0.4.9
    - jaxlib
    - numpy
    - pyyaml
    - tensorstore >=0.1.51
    - nest-asyncio
    - protobuf
    - importlib_resources

test:
  imports:
    - orbax.checkpoint
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Orbax Checkpoint
  home: https://github.com/google/orbax
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
