{% set python_min = "3.10" %}
{% set name = "orbax-checkpoint" %}
{% set version = "0.11.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orbax_checkpoint-{{ version }}.tar.gz
  sha256: 6f7f2cd89644e1892f2adf17dfa2ad29253712b22374ca9d6b02129922d46795

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.5,<4
    - pip
  run:
    - simplejson >=3.16.0
    - python >={{ python_min }}
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jax >=0.5.0
    - numpy
    - pyyaml
    - tensorstore >=0.1.71
    - nest-asyncio
    - protobuf
    - humanize
    - importlib_resources

test:
  imports:
    - orbax.checkpoint
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Orbax Checkpoint
  home: https://github.com/google/orbax
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - bwohlberg
