{% set python_min = '3.10' %}
{% set name = "orbax-checkpoint" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orbax_checkpoint-{{ version }}.tar.gz
  sha256: 366b4d528a7322e1b3d9ddcaed45c8515add0d2fc69c8975c30d98638543240f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.5,<4
    - pip
  run:
    - python >={{ python_min }}
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jax >=0.4.26
    - numpy
    - pyyaml
    - tensorstore >=0.1.60
    - nest-asyncio
    - protobuf
    - humanize
    - importlib_resources

test:
  imports:
    - orbax.checkpoint
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Orbax Checkpoint
  home: https://github.com/google/orbax
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - bwohlberg
