{% set name = "orbax-checkpoint" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orbax_checkpoint-{{ version }}.tar.gz
  sha256: 0754ecc2e5fc858e62bbcf610606502d8e1c9ada7295d9bb49cc172f884b0b1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - flit-core >=3.5,<4
    - pip
  run:
    - python >=3.10
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jaxlib >=0.4.34
    - jax >=0.4.34
    - numpy
    - pyyaml
    - tensorstore >=0.1.60
    - nest-asyncio
    - protobuf
    - importlib_resources

test:
  imports:
    - orbax.checkpoint
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Orbax Checkpoint
  home: https://github.com/google/orbax
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
