schema_version: 1

context:
  version: 0.11.34
  python_min: '3.11'

package:
  name: orbax-checkpoint
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/orbax-checkpoint/orbax_checkpoint-${{ version }}.tar.gz
  sha256: ab7733a0839085b93fe7cb52ef9596c7b6f8310df4e234c75588289704367888

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.5,<4
    - pip
  run:
    - python >=${{ python_min }}
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jax >=0.6.0
    - numpy
    - pyyaml
    - tensorstore >=0.1.74
    - importlib_resources
    - protobuf
    - humanize
    - aiofiles
    - simplejson >=3.16.0
    - psutil
    - uvloop
    - flax

tests:
  - python:
      imports:
        - orbax.checkpoint
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Orbax Checkpoint
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/google/orbax

extra:
  recipe-maintainers:
    - flferretti
    - jan-janssen
    - bwohlberg
