schema_version: 1

context:
  version: "0.9.0"
  python_min: "3.10"

package:
  name: orbax-checkpoint
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/orbax-checkpoint/orbax_checkpoint-${{ version }}.tar.gz
  sha256: b4fd3fa861d109af48ed65d8ed45e5d9869784a752eadbd8022731cb37cb29b8
  patches:
    - use-jax.errors.JaxRuntimeError.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.5,<4
    - pip
  run:
    - python >=${{ python_min }}
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jax >=0.4.35
    - numpy
    - pyyaml
    - tensorstore >=0.1.60
    - nest-asyncio
    - protobuf
    - humanize
    - importlib_resources

tests:
  - python:
      imports:
        - orbax.checkpoint
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Orbax Checkpoint
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/google/orbax

extra:
  recipe-maintainers:
    - jan-janssen
    - bwohlberg
